### ISSUE TITLE
add CLAM support?

### ISSUE THREAD

**Issue by dooglus** [dcpos/bip39#10]
I forked this repository a while ago (before you removed the wallet-specific tabs), hacked out a huge chunk of unused code (encryption, message and transaction signing, verifying, md5, etc.) and added CLAM support, but realise it would be better to have CLAM added to your site rather than have it in an increasingly out-of-date fork.

CLAM: http://clamclient.com/ | https://github.com/nochowderforyou/clams/ | https://bitcointalk.org/index.php?topic=623147

My fork: https://dooglus.github.io/bip39/ uses this for the CLAM fields:

    clam: {
      bip32: {
        public: 0xa8c26d64,
        private: 0xa8c17826
      },
      pubKeyHash: 0x89,
      wif: 0x85,
    }

Note that the other fields are unused in the BIP39 app. I'm unaware of a standard BIP32 coin number for CLAM, or standard magic numbers. I picked 4 for the coin number, since the version I forked used 0 through 3, and picked magic numbers such that the keys start "cpubk" and "cprvk". Nobody's using this yet, so feel free to assign whichever coin number seems appropriate.

**Comment by iancoleman** [comment]
I think the BIP44 coin number for clam is 23

http://doc.satoshilabs.com/slips/slip-0044.html

Thanks for the info, one day I'm hoping to add all the BIP44 registered coins if possible, but I have yet to track down the network specs for them.

**Comment by dooglus** [comment]
Thanks for the link. I hadn't seen that site before.

I note at the end it is written:
  "Coin types will be added only if there is a wallet implementing BIP-0044 for desired coin"

I'm not aware of any such wallet for CLAM - but I guess they're talking about the same altcoin as me. There is some scope for confusion, because http://getclams.com/ is NOT the same coin.

Would you be open to merging a pull-request that adds CLAMs if I create it?

**Comment by iancoleman** [comment]
Definitely open to pull requests.

I recommend having a look at https://github.com/dcpos/bip39/blob/master/src/js/bitcoinjs-extensions.js

**Comment by dooglus** [comment]
See #15.

I added a comment in the CLAM source repository giving the same version bytes: https://github.com/nochowderforyou/clams/commit/872b5cff

**Comment by iancoleman** [comment]
Merged https://github.com/dcpos/bip39/pull/15, thanks.
