### ISSUE TITLE
"Number of words" dropdown should only allow multiples of 3

### ISSUE THREAD

**Issue by tphyahoo** [dcpos/bip39#17]
Just a usability / gui thing.

It already drops from whatever the counter says, to the next lowest multiple of 3.

This would just communicate to users that it needs to be multiple of 3, in a more obvious way, for those unfamiliar with the workings of bip32.

**Comment by iancoleman** [comment]
This is a good idea.

I can envisage a few different approaches:

* Use a `select` tag. However, this reduces flexibility. If someone wants a 48 or 300 word mnemonic, the number of options will have to be massive.

* Add a `step="3"` attribute on the input so it only changes by multiples of 3. This doesn't assist with communicating the need for multiples of three, but it does allow for much more flexible mnemonic sizes.

* Add [`help-text`](http://getbootstrap.com/css/#forms-help-text) to the form, linking to [the reason for multiples of three](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic).

I prefer the `step` attribute with `help-text`; let me know your thoughts.

**Comment by tphyahoo** [comment]
I think help-text is a good idea, but the bip32 spec is pretty unfriendly, so I would pare it down to the essentials. Either put it in a tooltip/mouseover, and/or if there is an faq put it in the faq and link to the full spec from the faq.

pared down explanation:

"Q: Why are bip32 pass phrases always a multiple of 3 words long? 
 A: bip32 entropy seeds are sequences of 32 bits of entropy and 1 bit of checksum, for a total of 33 bits for each chunk of the sequence. So seed is always 3*x bits long.  Each word codes 11 bits of entropy, so pass phrases are 3 * x words long. BIP32 SPEC link. PS: Use 12 words for safety. 6 might be safe for small amounts of bitcoin, and 3 is definitely not safe!" with a link at the end there.  "

**Comment by tphyahoo** [comment]
No one is going to want more than 24 words mnemonic, that's just silly

https://en.wikipedia.org/wiki/Password_strength#Required_Bits_of_Entropy

Have options for 6, 12, 18, and 24 words. Good enough.

(128 should be default imho.)

**Comment by iancoleman** [comment]
Good point about required entropy.

I've kept the default strength as 15 based on https://github.com/dcpos/bip39/issues/11

Thanks for your input!
