### ISSUE TITLE
No way to go back, if you lose the mnemonic but have the seed?

### ISSUE THREAD

**Issue by GlassGhost** [dcpos/bip39#22]
It gives random mnemonic code -> seed functionality,  
but no way to go back, if you lose the mnemonic but have the seed?

We need seed -> mnemonic code functionality on the page, or is it there an I'm not seeing it?

**Comment by iancoleman** [comment]
Any particular reason for closing this?

I think it's a good feature and could be implemented similarly to [brainwallet.org](https://web.archive.org/web/20150707020924/https://brainwallet.org/), which can generate an address using several different sources.

**Comment by GlassGhost** [comment]
@iancoleman I read into this, and thought it was impossible.

**Comment by iancoleman** [comment]
Yeah sorry I confused the hex encoding of mnemonics with the BIP32 seed that comes from it. You're right that BIP32 seed cannot be reversed into a BIP39 seed.
