### ISSUE TITLE
BIP32 tab shows BIP44 addresses immediately after selecting coin

### ISSUE THREAD

**Issue by dooglus** [dcpos/bip39#23]
To reproduce:

1. visit https://dcpos.github.io/bip39/
2. generate random mnemonic
3. select BIP32 tab - see BIP32 addresses with paths m/0/0, m/0/1, etc.
4. switch coin from Bitcoin to Litecoin
5. BIP32 tab is now displaying BIP44 addresses with paths m/44'/2'/0'/0/0, m/44'/2'/0'/0/1, etc.
6. switch to BIP44 tab and back to BIP32 tab; this fixes the display back to m/0/0, etc.

Step 5 is the error. I want the BIP32 tab to show BIP32 addresses, not BIP44.

**Comment by iancoleman** [comment]
Thanks for this. Highlights a need for refactoring and automated tests, hopefully I will find time to attend to that soon.

**Comment by dooglus** [comment]
I don't think your fix is right. Now when I change the coin from Bitcoin to CLAM the derivation path stays the same: m/44'/0'/... I would expect it to change to m/44'/23'/... or whatever the number is for CLAM. That's what it used to do.

**Comment by iancoleman** [comment]
Thanks for persisting with this. I've simplified the detection of the derivation path so should be all good now. See https://github.com/dcpos/bip39/commit/38523d36dcce2c11baaf8dd742d02b94c41c7b23

**Comment by dooglus** [comment]
Looks good. Thanks.
