### ISSUE TITLE
How about supporting Bitcoin Core's derivation paths?

### ISSUE THREAD

**Issue by dooglus** [dcpos/bip39#25]
The forthcoming 0.13 release of Bitcoin Core introduces elementary support for BIP32. I've been using a modified version of your site to test the addresses it generates.

I needed to modify it because Core uses "hardened" derivation for the index of each address as well as for each part of the path.

So the first address it generates is `m/0'/0'/0'`, the 2nd is `m/0'/0'/1'`, etc.

The change I made is to simply generate an address from each of `$path/$index` and `$path/$index'` (note the trailing quote) for each index:

         function TableRow(index) {
     
             function init() {
    -            calculateValues();
    +            calculateValues(false);
    +            calculateValues(true);
             }
     
    -        function calculateValues() {
    +        function calculateValues(hardenedIndex) {
                 setTimeout(function() {
    -                var key = bip32ExtendedKey.derive(index);
    +                var key = hardenedIndex ? bip32ExtendedKey.deriveHardened(index) : bip32ExtendedKey.derive(index);
                     var address = key.getAddress().toString();
                     var privkey = key.privKey.toWIF(network);
    -                addAddressToList(index, address, privkey);
    +                addAddressToList(index + (hardenedIndex ? "'" : ""), address, privkey);
                 }, 50)
             }

It's ugly and probably not how you want to do it (if at all). But maybe my clumsy implementation is helpful.

**Comment by iancoleman** [comment]
Great idea, I will implement this feature in the next release.

**Comment by iancoleman** [comment]
Implemented in https://github.com/dcpos/bip39/commit/146e089e28fbda936955ce74fc1f2214418633c5 `Hardened Addresses checkbox` and https://github.com/dcpos/bip39/commit/8786746ba4b11e6d459e80868cbb2ac5bde4114a `Bitcoin Core derivation path information`

Thanks for the idea.
