### ISSUE TITLE
When using a Root key derrived altcoins are incorrect

### ISSUE THREAD

**Issue by dangershony** [dcpos/bip39#26]
Hi I just found a bug where when using a root key the derived alt coins are not correct

Reproduce:
1. Generate a mnemonic
2. Select Viacoin and inspect the generated addresses
3. Copy the root key and paste in a new tab
4. Select Viacoin again
5. Notice the derived addresses are not the same

I think this may be because the network parameter is not set in the method calcBip32RootKeyFromBase58()

**Comment by dangershony** [comment]
Here is the fix
https://github.com/dcpos/bip39/pull/27

**Comment by iancoleman** [comment]
Merged https://github.com/dcpos/bip39/pull/27

Thanks for the bug report and fix! I'll also add this to the page at dcpos.github.io/bip39/

**Comment by dangershony** [comment]
Awesome thanks, I'll be adding more coins with time.
