### ISSUE TITLE
xpub xpriv  Do they work?

### ISSUE THREAD

**Issue by brasslan** [dcpos/bip39#7]
When I put in 24 words plus a password, then I do get the same addresses listed that are in my current Mycelium wallet.

BUT  When I import the BIP32 Extended Key, aka either the xpub or the xpriv, into either Mycelium, or into Electrum, I get a different list of addresses.  They don't match the list on the web site.  When importing the extended key from this site into those two wallets, both wallets give the same address list, but it doesn't match the list shown on the website.  I'm using m/44'/0'/0'/0 for the path, I don't know why it shows a different list below.  Maybe backend programming isn't using the right path?

**Comment by brasslan** [comment]
I just found out,,,, if I take the root key from your site and punch it in over at bip32.org and then use the custom path m/44'/0'/0'/0/0/ then bip32.org reports the address that electrum reports when I take the xpub key from your website using the path m/44'/0'/0'/0/

I'm not much of a bitcoin genius, I only pretend sometimes.....  But I think maybe your website is reporting the extended keys for m/44'/0'/0'/0/0/ when it should instead be reporting m/44'/0'/0'/0/???  What do you think?

**Comment by iancoleman** [comment]
Thanks for looking into this.

> if I take the root key from your site and punch it in over at bip32.org and then use the custom path m/44'/0'/0'/0/0/ then bip32.org reports the address that electrum reports when I take the xpub key from your website using the path m/44'/0'/0'/0/

The address index on this site should be included in the derivation path used on bip32.org

For example, the third address (index two) generated by mycelium has a derivation path of `m/44'/0'/0'/0/2`, which on this site is the third row for the derivation path of `m/44'/0'/0'/0`.

I think this confusion would be resolved by renaming the `index` column of the table to `path` and changing the value from `2` to `m/44'/0'/0'/0/2` (or whatever the path is for that address).

Does this sound like the sort of change that would make this page easier to understand and use?

**Comment by brasslan** [comment]
On further inspection, your site is returning the same data as bip32.org.  So I think the math must be right.   I believe that I'm getting confused because of one thing.  If I import the xprv into mycelium, then I expect to have the first address in the wallet match the address listed on the website for the path m/44'/0'/0'/0/    But instead, I have to change the path to m/44'/0'/0'/ and then take that xprv key and import into mycelium to get the right address.     

If you didn't quite catch that, here is a full example.

I ask the website to generate 12 words.
cement saddle token wolf extend owner unable clinic live belt tumble always

I hit restore in mycelium and after typing in the 12 words then the app agrees with the website and reports the first address to be 
1FN31FJcCCmfnUFxMUqzaXfWF24g9RmEPK

BUT if I DON'T type in the 12 words, and instead import the xpriv key
xprvA1KhLBXMNdjTf63nh1LJxZTKpjC3wBsrBuceh3JtNHes75EM5yqSmS6PJ7zTVvbu176527C27qZwdQ1UzwbezTphPPKMzx9BDo61S2dRLg6
then mycelium instead reports the first address to be
1Ao2hJ2LocA6CGQrM34wa9yvKT7NyUUPaV

In order to get the website to show that address, then I have to change the path to read
m/44'/0'/0'/0/0

Or in order to import an xprv into mycelium and get the correct address of 
1FN31FJcCCmfnUFxMUqzaXfWF24g9RmEPK
then I have to instead change the path on the website to read
m/44'/0'/0'/
and then import that xprv into the wallet
xprv9zG5T5RR9vznxCybL2WNREdwB6KrVPktUUA19fQb2HxbZHMhHHxB8AosKhuEyY6eMCvnVo3n4cjHocr7uf2rZ74mpH3siVsMpRngXfkVwjR


So I've come to the conclusion that this is how it's supposed to be.  It isn't a mycelium thing, because I get the same addresses when importing the xpriv into electrum as well.   I don't currently understand why, but I'll do some more reading and searching and reading to see what I can find.  Thank you for making this website!  I'm learning a LOT about HD and bip32 and 44.

**Comment by brasslan** [comment]
Maybe I have it figured out?  What I want in the end is to export an xpub that my Dad can deposit into every month. m/44'/0'/0'/0/x   Then, when I spend an output, I don't want him to be able to see the change addresses inside of m/44'/0'/0'/1/x and then he will have trouble knowing what the balance is on the deposit account.  It would give me a little more privacy.

I'm guessing though that the xpub requires access to those change addresses so that end users don't freak out about mismatch balances on their watch only wallets.

So because mycelium and electrum and probably all the rest of the bip 32/44 wallets require the xpub to also see the change addresses, then when I get the xpub from the web calculator, I have to grab it from  m/44'/0'/0'/ instead of from   m/44'/0'/0'/0/ which is what I want to do for increased privacy.

But then,,,, what good is it to have the change addresses in a separate chain if I can't really separate them out.  Right now, it seams that both mycelium and electrum won't allow me to do that.

**Comment by iancoleman** [comment]
There's a change from 'Index' to 'Path' to hopefully make it clearer what is happening in the table of derived addresses/keys.
https://github.com/dcpos/bip39/commit/ae30fed8037fa9d1e88e9431c4f301f1d1c53d29

For now, I can't think of any better way to address this issue so will close it. If you can suggest anything that will improve your experience when using the app, feel free to add comments.

Thanks for your input.
