### ISSUE TITLE
incorrect derivation path used when switching coins using dropdown menu

### ISSUE THREAD

**Issue by dooglus** [dcpos/bip39#9]
To reproduce:

* visit https://dcpos.github.io/bip39/
* enter 'belt belt belt' as mnemonic
* select Litecoin from the coin menu
* examine BIP44 tab
* a) note derivation path: `m/44'/2'/0'/0` and extended key: `Ltpv7AGXcL...`
* change 'coin' input field on BIP44 tab from 2 to 0
* b) note derivation path: `m/44'/0'/0'/0` and extended key: `Ltpv7AGXcL...`
* change 'coin' input field on BIP44 tab back to 2
* c) note derivation path: `m/44'/2'/0'/0` and extended key: `Ltpv7AG3oy...`
* change 'coin' input field on BIP44 tab back to 0, then switch to 'Bitcoin' and back to 'Litecoin' in the menu near the top of the page
* d) note derivation path: `m/44'/2'/0'/0` and extended key: `Ltpv7AGXcL...`
 
b) and c) are correct. a) and d) both have the derivation path from c) but the extended key from b).

The problem appears to be that `networkChanged()` calls `setBip44DerivationPath()` which updates the DOM but doesn't modify the `derivationPath` global.

Moving the `derivationPath = DOM.bip44path.val();` from `bip44Changed()` into `setBip44DerivationPath()` would probably fix the problem.

**Comment by iancoleman** [comment]
Thanks for this, good find. I'll also add a test suite which really should have been there a long time ago!
